# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: '\.git/|__pycache__/|\.pyc'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: file-contents-sorter
        files: \.gitignore
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix, --indent=4, --no-sort-keys]
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.5.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=120]
        exclude: migrations/

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/Instagram/Fixit
    rev: v2.0.0.post1
    hooks:
      - id: fixit-fix

  # Ruff replaces flake8 and pylint and more
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.275
    hooks:
      - id: ruff
