---
name: "AICodeBot Code Review"
author: Nick Sullivan @gorillamania
description: "AI to review code in commits and pull requests"
branding:
  icon: "code"
  color: "green"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  openai_api_key:
    description: "OpenAI API Key"
    required: true

outputs:
  review_status:
    description: "The status of the code review"
  review_comments:
    description: "The comments from the code review"

runs:
  using: "docker"
  image: "Dockerfile"
