---
name: "AICodeBot Code Review"
description: "AI to review code in commits and pull requests"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  openai_api_key:
    description: "OpenAI API Key"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
