---
name: "AICodeBot Code Review"
author: Nick Sullivan @TechNickAI
description: "AI to review code in commits and pull requests"
branding:
  icon: "code"
  color: "green"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  anthropic_api_key:
    description: "Anthropic API Key"
    required: false
  openai_api_key:
    description: "OpenAI API Key"
    required: false
  aicodebot_personality:
    description: "The personality of the AICodeBot to respond with"
    required: false
    default: "Her"
  comment_on_passed:
    # Not recommended, as it can be noisy - it will send an email to the committer on every commit
    description: "Create a comment on a PASSED review"
    required: false

outputs:
  review_status:
    description: "The status of the code review"
  review_comments:
    description: "The comments from the code review"

runs:
  using: "docker"
  image: "Dockerfile"
